### ISSUE TITLE
SQL example needed

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-character-tools#2]
The module requires a SQL example for the item script

**Comment by Illuminati2739** [comment]
To my understanding, you can use a copy of a hearthstone, i tried it., doesn't work to my knowledge. I played with it for few hours and that character_tools script is not working

**Comment by poszer** [comment]
Example added https://github.com/azerothcore/mod-character-tools/commit/5cb7b261d60d81250512a3fc5f4a92a581431aba
